package bison.solutions.domain.smaller.things.tiny.things;

import java.io.Serializable;

public class Properties implements Serializable {
    public String court_id;
    public String court_name;
    public String addr_1;
    public String city;
    public String state;
    public String zip;
    public String lat;
    public String lng;
    public String geo_code_status;
    public String phone;
    public String judge;
    public String prosecutor;
    public String court_clerk;
    public String hours;
    public String time_of_docket;
    public String sessions_per_month;
    public String total_population;
    public String demographics_white_percentage;
    public String demographics_black_percentage;
    public String demographics_asian_percentage;
    public String demographics_other_percentage;
    public String demographics_below_poverty_percentage;
    public String fines_percentage_of_gr;
    public String police_number;
    public String total_vehicle_stops;
    public String white_vehicle_stops;
    public String white_vehicle_stops_as_percentage;
    public String white_search_rate;
    public String white_contraband_hit_rate;
    public String white_arrest_rate;
    public String black_vehicle_stops;
    public String black_vehicle_stops_as_percentage;
    public String black_search_rate;
    public String black_contraband_hit_rate;
    public String black_arrest_rate;
    public String hispanic_vehicle_stops;
    public String hispanic_vehicle_stops_as_percentage;
    public String hispanic_search_rate;
    public String hispanic_contraband_hit_rate;
    public String hispanic_arrest_rate;
    public String asian_vehicle_stops;
    public String asian_vehicle_stops_as_percentage;
    public String asian_search_rate;
    public String asian_contraband_hit_rate;
    public String asian_arrest_rate;
    public String indian_vehicle_stops;
    public String indian_vehicle_stops_as_percentage;
    public String indian_search_rate;
    public String indian_contraband_hit_rate;
    public String indian_arrest_rate;
    public String other_vehicle_stops;
    public String other_vehicle_stops_as_percentage;
    public String other_search_rate;
    public String other_contraband_hit_rate;
    public String other_arrest_rate;
    public String tmp;
    public String muni_geo_id;
    public String icon_url;
}
